metadata:
  labels:
    app: camel-quarkus-openapi
    app.openshift.io/runtime: camel
  name: camel-quarkus-openapi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: camel-quarkus-openapi
  template:
    metadata:
      annotations:
      labels:
        app: camel-quarkus-openapi
    spec:
      containers:
        - resources:
            requests:
              cpu: 0.05
              memory: 256Mi
            limits:
              cpu: 1
              memory: 256Mi
          env:
          - name: JAEGER_SERVICE_NAME
            value: 'camel-quarkus-openapi'
          - name: JAEGER_AGENT_HOST
            value: 'jaeger-all-in-one-inmemory-agent'
          - name: JAEGER_SAMPLER_PARAM
            value: '1.0'
